export const wordbank = [
  {
    type: 'department',
    nameEN: "Governor's Office",
    nameBM: 'Pejabat Gabenor',
    acronymEN: '',
    acronymBM: 'GOV',
  },
  {
    type: 'department',
    nameEN: 'Strategic Communications',
    nameBM: 'Jabatan Komunikasi Strategik',
    acronymEN: '',
    acronymBM: 'JKK',
  },
  {
    type: 'department',
    nameEN: 'Consumer and Market Conduct',
    nameBM: 'Jabatan Konsumer dan Amalan Pasaran',
    acronymEN: 'CMC',
    acronymBM: 'JKAP',
  },
  {
    type: 'department',
    nameEN: 'Financial Conglomeration Supervision',
    nameBM: 'Jabatan Penyeliaan Konglomerat Kewangan',
    acronymEN: '',
    acronymBM: 'JP1',
  },
  {
    type: 'department',
    nameEN: 'Banking Supervision',
    nameBM: 'Jabatan Penyeliaan Perbankan',
    acronymEN: '',
    acronymBM: 'JP2',
  },
  {
    type: 'department',
    nameEN: 'Insurance and Takaful Supervision',
    nameBM: 'Jabatan Penyeliaan Insurans dan Takaful',
    acronymEN: '',
    acronymBM: 'JP3',
  },
  {
    type: 'department',
    nameEN: 'Finance',
    nameBM: 'Jabatan Kewangan',
    acronymEN: 'FINANCE',
    acronymBM: 'JKW',
  },
  {
    type: 'department',
    nameEN: 'Prudential Financial Policy',
    nameBM: 'Jabatan Dasar Kewangan Pruden',
    acronymEN: 'PFP',
    acronymBM: 'JDKP',
  },
  {
    type: 'department',
    nameEN: 'Facility Management Services',
    nameBM: 'Perkhidmatan Pengurusan Fasiliti',
    acronymEN: '',
    acronymBM: 'JPF',
  },
  {
    type: 'department',
    nameEN: 'Islamic Banking and Takaful',
    nameBM: 'Jabatan Perbankan Islam dan Takaful',
    acronymEN: '',
    acronymBM: 'JPIT',
  },
  {
    type: 'department',
    nameEN: 'Strategic Human Capital',
    nameBM: 'Jabatan Modal Insan Strategik',
    acronymEN: '',
    acronymBM: 'JMIS',
  },
  {
    type: 'department',
    nameEN: 'Risk Management',
    nameBM: 'Jabatan Pengurusan Risiko',
    acronymEN: 'RMD',
    acronymBM: '',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Jabatan Digital Dan Teknologi',
    acronymEN: '',
    acronymBM: 'JDT',
  },
  {
    type: 'department',
    nameEN: 'Human Capital Development Centre',
    nameBM: 'Pusat Pembangunan Modal Insan',
    acronymEN: 'HCDC',
    acronymBM: '',
  },
  {
    type: 'department',
    nameEN: 'LINK and BNM Offices',
    nameBM: 'Jabatan LINK dan Pejabat BNM',
    acronymEN: 'LINK',
    acronymBM: 'JLPB',
  },
  {
    type: 'department',
    nameEN: 'Internal Audit',
    nameBM: 'Jabatan Audit Dalam',
    acronymEN: 'IAD',
    acronymBM: 'JAD',
  },
  {
    type: 'department',
    nameEN: 'Organisational Security Management',
    nameBM: 'Jabatan Pengurusan Keselamatan Organisasi',
    acronymEN: 'OSeM',
    acronymBM: '',
  },
  {
    type: 'department',
    nameEN: 'Investment Operations and Financial Markets',
    nameBM: 'Jabatan Operasi Pelaburan dan Pasaran Kewangan',
    acronymEN: '',
    acronymBM: 'JOPPK',
  },
  {
    type: 'department',
    nameEN: 'Economics',
    nameBM: 'Jabatan Ekonomi',
    acronymEN: '',
    acronymBM: 'JEK',
  },
  {
    type: 'department',
    nameEN: 'Monetary Policy',
    nameBM: 'Jabatan Dasar Monetari',
    acronymEN: '',
    acronymBM: 'JDM',
  },
  {
    type: 'department',
    nameEN: 'International',
    nameBM: 'Jabatan Antarabangsa',
    acronymEN: '',
    acronymBM: 'JA',
  },
  {
    type: 'department',
    nameEN: 'Data Management and Statistics',
    nameBM: 'Jabatan Perkhidmatan Statistik',
    acronymEN: '',
    acronymBM: 'JPS',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Unit Khas Penyeliaan Koperasi',
    acronymEN: '',
    acronymBM: 'UKPK',
  },
  {
    type: 'department',
    nameEN: 'Insurance Development',
    nameBM: 'Jabatan Pembangunan Insurans',
    acronymEN: 'IDD',
    acronymBM: '',
  },
  {
    type: 'department',
    nameEN: 'Risk Specialist and Technology Supervision',
    nameBM: 'Jabatan Pakar Risiko dan Penyeliaan Teknologi',
    acronymEN: 'RSTS',
    acronymBM: 'JPRPT',
  },
  {
    type: 'department',
    nameEN: 'Money Services Business Regulation',
    nameBM: 'Jabatan Pengawalan Perniagaan Perkhidmatan Wang',
    acronymEN: 'MSBR',
    acronymBM: 'JPPPW',
  },
  {
    type: 'department',
    nameEN: 'Financial Surveillance',
    nameBM: 'Jabatan Pemantauan dan Pengawasan Kewangan',
    acronymEN: 'FS',
    acronymBM: 'JPPK',
  },
  {
    type: 'department',
    nameEN: 'Payments Oversight',
    nameBM: 'Jabatan Pemantauan Pembayaran',
    acronymEN: '',
    acronymBM: 'JPP',
  },
  {
    type: 'department',
    nameEN: 'Financial Development and Innovation',
    nameBM: 'Jabatan Pembangunan dan Inovasi Kewangan',
    acronymEN: 'FDI',
    acronymBM: 'JPSKI',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Jabatan Perisikan Kewangan dan Penguatkuasaan',
    acronymEN: 'FIED',
    acronymBM: 'JPKP',
  },
  {
    type: 'department',
    nameEN: 'Development Finance and Inclusion',
    nameBM: 'Jabatan Kewangan Pembangunan dan Rangkuman Kewangan',
    acronymEN: 'DFINC',
    acronymBM: '',
  },
  {
    type: 'department',
    nameEN: 'Centralised Shared Services Management Office',
    nameBM: '',
    acronymEN: 'CSSO',
    acronymBM: '',
  },
  {
    type: 'department',
    nameEN: 'Foreign Exchange Policy',
    nameBM: 'Jabatan Pentadbiran Pertukaran Asing',
    acronymEN: '',
    acronymBM: 'JPPA',
  },
  {
    type: 'department',
    nameEN: 'Human Capital Services',
    nameBM: 'Perkhidmatan Modal Insan',
    acronymEN: 'HCS',
    acronymBM: '',
  },
  {
    type: 'department',
    nameEN: 'Legal',
    nameBM: 'Jabatan Undang-Undang',
    acronymEN: '',
    acronymBM: 'JUN',
  },
  {
    type: 'department',
    nameEN: 'Museum, Art Gallery & KMC Services',
    nameBM: '',
    acronymEN: 'MAG',
    acronymBM: '',
  },
  {
    type: 'department',
    nameEN: 'Hospitality Services',
    nameBM: 'Perkhidmatan Hospitaliti',
    acronymEN: '',
    acronymBM: 'HOS',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Kilang Wang Bank Negara Malaysia',
    acronymEN: '',
    acronymBM: 'KWBNM',
  },
  {
    type: 'department',
    nameEN: 'Automated Cash Centre',
    nameBM: '',
    acronymEN: 'ACC',
    acronymBM: '',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Koperasi Kredit & Pelaburan Kakitangan BNM Berhad',
    acronymEN: '',
    acronymBM: 'KOOP',
  },
  {
    type: 'department',
    nameEN: 'Currency Management and Operations',
    nameBM: 'Jabatan Pengurusan dan Operasi Matawang',
    acronymEN: '',
    acronymBM: 'JPW',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Pejabat BNM Johor Bahru',
    acronymEN: '',
    acronymBM: 'BNMJB',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Pejabat BNM Pulau Pinang',
    acronymEN: '',
    acronymBM: 'BNMPP',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Pejabat BNM Kota Kinabalu',
    acronymEN: '',
    acronymBM: 'BNMKK',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Pejabat BNM Kuching',
    acronymEN: '',
    acronymBM: 'BNMKC',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Pejabat BNM Kuala Terengganu',
    acronymEN: '',
    acronymBM: 'BNMKT',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Agensi Kaunseling dan Pengurusan Kredit',
    acronymEN: '',
    acronymBM: 'AKPK',
  },
  {
    type: 'department',
    nameEN: 'Payments Network Malaysia Sdn Bhd (PayNet)',
    nameBM: '',
    acronymEN: 'PAYNET',
    acronymBM: '',
  },
  {
    type: 'department',
    nameEN: 'The Islamic Financial Services Board',
    nameBM: '',
    acronymEN: 'IFSB',
    acronymBM: '',
  },
  {
    type: 'department',
    nameEN: 'The SEACEN Centre',
    nameBM: '',
    acronymEN: 'SEACEN',
    acronymBM: '',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Jabatan Audit Negara',
    acronymEN: '',
    acronymBM: 'JAN',
  },
  {
    type: 'department',
    nameEN: 'Administration Unit - Financial Sector',
    nameBM: 'Unit Pentadbiran Sektor Kewangan',
    acronymEN: '',
    acronymBM: 'UPSK',
  },
  {
    type: 'department',
    nameEN: 'Administration Unit - Monetary Sector',
    nameBM: 'Unit Pentadbiran Sektor Monetori',
    acronymEN: 'MSSA',
    acronymBM: '',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: '',
    acronymEN: '',
    acronymBM: '',
  },
]
