export const wordbank = [
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Pejabat Gabenor',
    acronymEN: '',
    acronymBM: 'GOV',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Jabatan Komunikasi Strategik',
    acronymEN: '',
    acronymBM: 'JKK',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Jabatan Konsumer dan Amalan Pasaran',
    acronymEN: 'CMC',
    acronymBM: 'JKAP',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Jabatan Penyeliaan Konglomerat Kewangan',
    acronymEN: '',
    acronymBM: 'JP1',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Jabatan Penyeliaan Perbankan',
    acronymEN: '',
    acronymBM: 'JP2',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Jabatan Kewangan',
    acronymEN: 'FINANCE',
    acronymBM: 'JKW',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Jabatan Dasar Kewangan Pruden',
    acronymEN: 'PFP',
    acronymBM: 'JDKP',
  },
  {
    type: 'department',
    nameEN: 'Facility Management Services',
    nameBM: 'Perkhidmatan Pengurusan Fasiliti',
    acronymEN: '',
    acronymBM: 'JPF',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Jabatan Perbankan Islam dan Takaful',
    acronymEN: '',
    acronymBM: 'JPIT',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Jabatan Modal Insan Strategik',
    acronymEN: '',
    acronymBM: 'JMIS',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Jabatan Pengurusan Risiko',
    acronymEN: 'RMD',
    acronymBM: '',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Jabatan Digital Dan Teknologi',
    acronymEN: '',
    acronymBM: 'JDT',
  },
  {
    type: 'department',
    nameEN: 'Human Capital Development Centre',
    nameBM: 'Pusat Pembangunan Modal Insan',
    acronymEN: 'HCDC',
    acronymBM: '',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Jabatan Penyeliaan Insurans dan Takaful',
    acronymEN: '',
    acronymBM: 'JP3',
  },
  {
    type: 'department',
    nameEN: 'LINK and BNM Offices',
    nameBM: 'LINK dan Pejabat BNM',
    acronymEN: 'LINK',
    acronymBM: '',
  },
  {
    type: 'department',
    nameEN: 'Internal Audit',
    nameBM: 'Jabatan Audit Dalam',
    acronymEN: 'IAD',
    acronymBM: 'JAD',
  },
  {
    type: 'department',
    nameEN: 'Organisational Security Management',
    nameBM: 'Jabatan Pengurusan Keselamatan Organisasi',
    acronymEN: 'OSeM',
    acronymBM: '',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Jabatan Operasi Pelaburan dan Pasaran Kewangan',
    acronymEN: '',
    acronymBM: 'JOPPK',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Jabatan Ekonomi',
    acronymEN: '',
    acronymBM: 'JEK',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Jabatan Dasar Monetari',
    acronymEN: '',
    acronymBM: 'JDM',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Jabatan Antarabangsa',
    acronymEN: '',
    acronymBM: 'JA',
  },
  {
    type: 'department',
    nameEN: 'Data Management and Statistics',
    nameBM: 'Jabatan Perkhidmatan Statistik',
    acronymEN: '',
    acronymBM: 'JPS',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: 'Unit Khas Penyeliaan Koperasi',
    acronymEN: '',
    acronymBM: 'UKPK',
  },
  {
    type: 'department',
    nameEN: 'Insurance Development',
    nameBM: 'Jabatan Pembangunan Insurans',
    acronymEN: 'IDD',
    acronymBM: '',
  },
  {
    type: 'department',
    nameEN: 'Risk Specialist and Technology Supervision',
    nameBM: 'Jabatan Pakar Risiko dan Penyeliaan Teknologi',
    acronymEN: 'RSTS',
    acronymBM: 'JPRPT',
  },
  {
    type: 'department',
    nameEN: 'Money Services Business Regulation',
    nameBM: 'Jabatan Pengawalan Perniagaan Perkhidmatan Wang',
    acronymEN: 'MSBR',
    acronymBM: 'JPPPW',
  },
  {
    type: 'department',
    nameEN: '',
    nameBM: '',
    acronymEN: '',
    acronymBM: '',
  },
]
