interface Lingotest {
  type: "department" | "unit" | "working group";
  department?: {
    bm?: string;
    en?: string;
  };
  description?: string;
  name: {
    bm?: string;
    en?: string;
  };
  acronym: {
    bm?: string;
    en?: string;
  };
  preferredAcronym?: "bm" | "en";
}

const test: Lingotest[] = [
  {
    type: "working group",
    name: {
      en: "Data Analytics Working Group",
    },
    description: "Working group for the DSA unit of JPS.",
    acronym: {
      en: "DAG",
    },
  },
  {
    type: "department",
    name: {
      bm: "Pejabat Gabenor",
      en: "Governor's Office",
    },
    acronym: {
      en: "GOV",
    },
    preferredAcronym: "en",
  },
  {
    type: "unit",
    department: {
      bm: "JPS",
    },
    name: {
      en: "Data Science and Analytics",
    },
    acronym: {
      en: "DSA",
    },
  },
];

export interface Lingo {
  type: "department" | "office" | "unit" | "sector" | "branch";
  nameEN: string;
  nameBM: string;
  acronymEN: string;
  acronymBM: string;
  preferredLang: "BM" | "EN";
}

export const lingobank: Lingo[] = [
  {
    type: "office",
    nameEN: "Governor's Office",
    nameBM: "Pejabat Gabenor",
    acronymEN: "",
    acronymBM: "GOV",
    preferredLang: "EN",
  },
  {
    type: "office",
    nameEN: "Ethics and Integrity Office",
    nameBM: "Pejabat Etika dan Integriti",
    acronymEN: "",
    acronymBM: "EIO",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "Internal Audit",
    nameBM: "Jabatan Audit Dalam",
    acronymEN: "IAD",
    acronymBM: "JAD",
    preferredLang: "BM",
  },
  {
    type: "department",
    nameEN: "Risk Management",
    nameBM: "Jabatan Pengurusan Risiko",
    acronymEN: "RMD",
    acronymBM: "",
    preferredLang: "EN",
  },
  {
    type: "unit",
    nameEN: "Monetary Stability Sector Administration",
    nameBM: "Unit Pentadbiran Sektor Monetori",
    acronymEN: "MSSA",
    acronymBM: "",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "Economics",
    nameBM: "Jabatan Ekonomi",
    acronymEN: "",
    acronymBM: "JEK",
    preferredLang: "BM",
  },
  {
    type: "department",
    nameEN: "Monetary Policy",
    nameBM: "Jabatan Dasar Monetari",
    acronymEN: "",
    acronymBM: "JDM",
    preferredLang: "BM",
  },
  {
    type: "department",
    nameEN: "International",
    nameBM: "Jabatan Antarabangsa",
    acronymEN: "",
    acronymBM: "JA",
    preferredLang: "BM",
  },
  {
    type: "department",
    nameEN: "Data Management and Statistics",
    nameBM: "Jabatan Perkhidmatan Data dan Statistik",
    acronymEN: "",
    acronymBM: "JPS",
    preferredLang: "BM",
  },
  {
    type: "department",
    nameEN: "Investment Operations and Financial Markets",
    nameBM: "Jabatan Operasi Pelaburan dan Pasaran Kewangan",
    acronymEN: "",
    acronymBM: "JOPPK",
    preferredLang: "BM",
  },
  {
    type: "department",
    nameEN: "Foreign Exchange Policy",
    nameBM: "Jabatan Pentadbiran Pertukaran Asing",
    acronymEN: "",
    acronymBM: "JPPA",
    preferredLang: "BM",
  },
  {
    type: "department",
    nameEN: "Financial Development and Innovation",
    nameBM: "Jabatan Pembangunan dan Inovasi Kewangan",
    acronymEN: "FDI",
    acronymBM: "JPSKI",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "Islamic Banking and Takaful",
    nameBM: "Jabatan Perbankan Islam dan Takaful",
    acronymEN: "",
    acronymBM: "JPIT",
    preferredLang: "BM",
  },
  {
    type: "department",
    nameEN: "Insurance Development",
    nameBM: "Jabatan Pembangunan Insurans",
    acronymEN: "IDD",
    acronymBM: "",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "Development Finance and Inclusion",
    nameBM: "Jabatan Kewangan Pembangunan dan Rangkuman Kewangan",
    acronymEN: "DFINC",
    acronymBM: "",
    preferredLang: "EN",
  },
  {
    type: "unit",
    nameEN: "Financial Sector Administration",
    nameBM: "Unit Pentadbiran Sektor Kewangan",
    acronymEN: "",
    acronymBM: "UPSK",
    preferredLang: "BM",
  },
  {
    type: "department",
    nameEN: "Financial Conglomerates Supervision",
    nameBM: "Jabatan Penyeliaan Konglomerat Kewangan",
    acronymEN: "",
    acronymBM: "JP1",
    preferredLang: "BM",
  },
  {
    type: "department",
    nameEN: "Banking Supervision",
    nameBM: "Jabatan Penyeliaan Perbankan",
    acronymEN: "",
    acronymBM: "JP2",
    preferredLang: "BM",
  },
  {
    type: "department",
    nameEN: "Insurance and Takaful Supervision",
    nameBM: "Jabatan Penyeliaan Insurans dan Takaful",
    acronymEN: "",
    acronymBM: "JP3",
    preferredLang: "BM",
  },
  {
    type: "department",
    nameEN: "Risk Specialist and Technology Supervision",
    nameBM: "Jabatan Pakar Risiko dan Penyeliaan Teknologi",
    acronymEN: "RSTS",
    acronymBM: "JPRPT",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "Payment Services Oversight",
    nameBM: "Jabatan Pemantauan Perkhidmatan Pembayaran",
    acronymEN: "POD",
    acronymBM: "JPP",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "Financial Surveillance",
    nameBM: "Jabatan Pemantauan dan Pengawasan Kewangan",
    acronymEN: "FS",
    acronymBM: "JPPK",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "Prudential Financial Policy",
    nameBM: "Jabatan Dasar Kewangan Pruden",
    acronymEN: "PFP",
    acronymBM: "JDKP",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "Consumer and Market Conduct",
    nameBM: "Jabatan Konsumer dan Amalan Pasaran",
    acronymEN: "CMC",
    acronymBM: "JKAP",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "Payment Services Policy",
    nameBM: "Jabatan Dasar Perkhidmatan Pembayaran",
    acronymEN: "",
    acronymBM: "",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "Strategic Communications",
    nameBM: "Jabatan Komunikasi Strategik",
    acronymEN: "",
    acronymBM: "JKK",
    preferredLang: "BM",
  },
  {
    type: "department",
    nameEN: "Legal",
    nameBM: "Jabatan Undang-Undang",
    acronymEN: "",
    acronymBM: "JUN",
    preferredLang: "BM",
  },
  {
    type: "department",
    nameEN: "Financial Intelligence and Enforcement",
    nameBM: "Jabatan Perisikan Kewangan dan Penguatkuasaan",
    acronymEN: "FIED",
    acronymBM: "JPKP",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "Strategic Human Capital",
    nameBM: "Jabatan Modal Insan Strategik",
    acronymEN: "",
    acronymBM: "JMIS",
    preferredLang: "BM",
  },
  {
    type: "department",
    nameEN: "Human Capital Development Centre",
    nameBM: "Pusat Pembangunan Modal Insan",
    acronymEN: "HCDC",
    acronymBM: "",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "Human Capital Services",
    nameBM: "Perkhidmatan Modal Insan",
    acronymEN: "HCS",
    acronymBM: "",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "Currency Management and Operations",
    nameBM: "Jabatan Pengurusan dan Operasi Mata Wang",
    acronymEN: "",
    acronymBM: "JPW",
    preferredLang: "BM",
  },
  {
    type: "department",
    nameEN: "Finance",
    nameBM: "Jabatan Kewangan",
    acronymEN: "FINANCE",
    acronymBM: "JKW",
    preferredLang: "BM",
  },
  {
    type: "department",
    nameEN: "LINK and BNM Offices",
    nameBM: "Jabatan LINK dan Pejabat BNM",
    acronymEN: "LINK",
    acronymBM: "JLPB",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "Centralised Procurement Unit",
    nameBM: "Unit Perolehan Berpusat",
    acronymEN: "",
    acronymBM: "",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "Facility Management Services",
    nameBM: "Perkhidmatan Pengurusan Fasiliti",
    acronymEN: "",
    acronymBM: "JPF",
    preferredLang: "BM",
  },
  {
    type: "department",
    nameEN: "Hospitality and Museum",
    nameBM: "Hospitaliti dan Muzium",
    acronymEN: "",
    acronymBM: "",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "Organisational Security Management",
    nameBM: "Jabatan Pengurusan Keselamatan Organisasi",
    acronymEN: "OSeM",
    acronymBM: "",
    preferredLang: "EN",
  },
  {
    type: "sector",
    nameEN: "Digital and Technology Sector",
    nameBM: "",
    acronymEN: "",
    acronymBM: "DTS",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "Business Technology",
    nameBM: "Teknologi Korporat",
    acronymEN: "",
    acronymBM: "",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "Digital Technology Infrastructure",
    nameBM: "Infrastruktur Teknologi Digital",
    acronymEN: "",
    acronymBM: "",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "Cyber Security",
    nameBM: "Keselamatan Siber",
    acronymEN: "CSD",
    acronymBM: "",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "Financial Market Infrastructure",
    nameBM: "Infrastruktur Pasaran Kewangan",
    acronymEN: "",
    acronymBM: "",
    preferredLang: "EN",
  },
  {
    type: "branch",
    nameEN: "",
    nameBM: "Pejabat BNM Johor Bahru",
    acronymEN: "",
    acronymBM: "BNMJB",
    preferredLang: "BM",
  },
  {
    type: "branch",
    nameEN: "",
    nameBM: "Pejabat BNM Pulau Pinang",
    acronymEN: "",
    acronymBM: "BNMPP",
    preferredLang: "BM",
  },
  {
    type: "branch",
    nameEN: "",
    nameBM: "Pejabat BNM Kota Kinabalu",
    acronymEN: "",
    acronymBM: "BNMKK",
    preferredLang: "BM",
  },
  {
    type: "branch",
    nameEN: "",
    nameBM: "Pejabat BNM Kuching",
    acronymEN: "",
    acronymBM: "BNMKC",
    preferredLang: "BM",
  },
  {
    type: "branch",
    nameEN: "",
    nameBM: "Pejabat BNM Kuala Terengganu",
    acronymEN: "",
    acronymBM: "BNMKT",
    preferredLang: "BM",
  },
];

const others: Lingo[] = [
  {
    type: "department",
    nameEN: "",
    nameBM: "",
    acronymEN: "",
    acronymBM: "",
    preferredLang: "BM",
  },
  {
    type: "department",
    nameEN: "Museum, Art Gallery & KMC Services",
    nameBM: "",
    acronymEN: "MAG",
    acronymBM: "",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "Hospitality Services",
    nameBM: "Perkhidmatan Hospitaliti",
    acronymEN: "",
    acronymBM: "HOS",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "",
    nameBM: "Unit Khas Penyeliaan Koperasi",
    acronymEN: "",
    acronymBM: "UKPK",
    preferredLang: "BM",
  },
  {
    type: "department",
    nameEN: "Centralised Shared Services Management Office",
    nameBM: "",
    acronymEN: "CSSO",
    acronymBM: "",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "",
    nameBM: "Kilang Wang Bank Negara Malaysia",
    acronymEN: "",
    acronymBM: "KWBNM",
    preferredLang: "BM",
  },
  {
    type: "department",
    nameEN: "Automated Cash Centre",
    nameBM: "",
    acronymEN: "ACC",
    acronymBM: "",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "",
    nameBM: "Koperasi Kredit & Pelaburan Kakitangan BNM Berhad",
    acronymEN: "",
    acronymBM: "KOOP",
    preferredLang: "BM",
  },
  {
    type: "department",
    nameEN: "",
    nameBM: "Agensi Kaunseling dan Pengurusan Kredit",
    acronymEN: "",
    acronymBM: "AKPK",
    preferredLang: "BM",
  },
  {
    type: "department",
    nameEN: "Payments Network Malaysia Sdn Bhd (PayNet)",
    nameBM: "",
    acronymEN: "PAYNET",
    acronymBM: "",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "The Islamic Financial Services Board",
    nameBM: "",
    acronymEN: "IFSB",
    acronymBM: "",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "The SEACEN Centre",
    nameBM: "",
    acronymEN: "SEACEN",
    acronymBM: "",
    preferredLang: "EN",
  },
  {
    type: "department",
    nameEN: "",
    nameBM: "Jabatan Audit Negara",
    acronymEN: "",
    acronymBM: "JAN",
    preferredLang: "BM",
  },
];
